from flask import Flask


def register_routes(app: Flask) -> None:
    from backend.routes import (
        anki,
        auth_me,
        auth_password_reset,
        bulk_characters,
        bulk_create_characters,
        bulk_create_words,
        chat,
        challenges,
        check_grammar_point,
        check_writing_sentence,
        check_writing_topic_relevance,
        complete_grammar_point,
        conversation_logs,
        create_character,
        create_word,
        delete_character,
        delete_knowledge_base,
        delete_user,
        delete_word,
        export_database,
        generate_article,
        get_grammar_point,
        get_hsk_level,
        health,
        ignore_hsk_word,
        list_characters,
        list_grammar_points,
        list_hsk_character_words,
        list_hsk_characters,
        list_users,
        list_words,
        pick_hsk_word,
        record_grammar_usage,
        reload_grammar_rules,
        reload_hsk_content,
        skip_grammar_point,
        smart_ai_preference,
        suggest_hsk_words,
        token_usage,
        update_character,
        update_user,
        update_word,
        upload_hsk_translation,
        weekly_articles,
        writing_practice,
    )
    from backend.utils.auth.user_context import register_user_context

    register_user_context(app)

    app.register_blueprint(health.bp)
    app.register_blueprint(auth_me.bp)
    app.register_blueprint(auth_password_reset.bp)
    app.register_blueprint(chat.bp)
    app.register_blueprint(conversation_logs.bp)
    app.register_blueprint(challenges.bp)
    app.register_blueprint(token_usage.bp)
    app.register_blueprint(anki.bp)
    app.register_blueprint(list_characters.bp)
    app.register_blueprint(create_character.bp)
    app.register_blueprint(bulk_create_characters.bp)
    app.register_blueprint(delete_character.bp)
    app.register_blueprint(update_character.bp)
    app.register_blueprint(list_words.bp)
    app.register_blueprint(create_word.bp)
    app.register_blueprint(bulk_create_words.bp)
    app.register_blueprint(update_word.bp)
    app.register_blueprint(delete_word.bp)
    app.register_blueprint(bulk_characters.bp)
    app.register_blueprint(export_database.bp)
    app.register_blueprint(delete_knowledge_base.bp)
    app.register_blueprint(list_grammar_points.bp)
    app.register_blueprint(get_grammar_point.bp)
    app.register_blueprint(writing_practice.bp)
    app.register_blueprint(skip_grammar_point.bp)
    app.register_blueprint(complete_grammar_point.bp)
    app.register_blueprint(check_grammar_point.bp)
    app.register_blueprint(check_writing_sentence.bp)
    app.register_blueprint(check_writing_topic_relevance.bp)
    app.register_blueprint(record_grammar_usage.bp)
    app.register_blueprint(list_hsk_characters.bp)
    app.register_blueprint(list_hsk_character_words.bp)
    app.register_blueprint(get_hsk_level.bp)
    app.register_blueprint(pick_hsk_word.bp)
    app.register_blueprint(suggest_hsk_words.bp)
    app.register_blueprint(ignore_hsk_word.bp)
    app.register_blueprint(list_users.bp)
    app.register_blueprint(update_user.bp)
    app.register_blueprint(delete_user.bp)
    app.register_blueprint(reload_hsk_content.bp)
    app.register_blueprint(upload_hsk_translation.bp)
    app.register_blueprint(reload_grammar_rules.bp)
    app.register_blueprint(smart_ai_preference.bp)
    app.register_blueprint(generate_article.bp)
    app.register_blueprint(weekly_articles.bp)
