"""Pinyin helpers for Anki pull (validation + accent → tone digit)."""

from __future__ import annotations

from typing import TypedDict

# Accented characters found in Anki pinyin fields → plain vowel + tone digit.
# Add more rows as needed (ā/á/ǎ/à, ē/é/ě/è, ō/ó/ǒ/ò, ū/ú/ǔ/ù, ǖ/ǘ/ǚ/ǜ, …).
PINYIN_ACCENT_MAP: list[dict[str, str]] = [
    {
        "problematic_char": "ī",
        "corresponding_char": "i",
        "corresponding_tone": "1",
    },
    {
        "problematic_char": "í",
        "corresponding_char": "i",
        "corresponding_tone": "2",
    },
    {
        "problematic_char": "ǐ",
        "corresponding_char": "i",
        "corresponding_tone": "3",
    },
    {
        "problematic_char": "ì",
        "corresponding_char": "i",
        "corresponding_tone": "4",
    },
    {
        "problematic_char": "à",
        "corresponding_char": "a",
        "corresponding_tone": "4",
    },
    {
        "problematic_char": "á",
        "corresponding_char": "a",
        "corresponding_tone": "2",
    },
    {
        "problematic_char": "ǎ",
        "corresponding_char": "a",
        "corresponding_tone": "3",
    },
    {
        "problematic_char": "à",
        "corresponding_char": "a",
        "corresponding_tone": "4",
    },
    {
        "problematic_char": "ē",
        "corresponding_char": "e",
        "corresponding_tone": "1",
    },
    {
        "problematic_char": "é",
        "corresponding_char": "e",
        "corresponding_tone": "2",
    },
    {
        "problematic_char": "ě",
        "corresponding_char": "e",
        "corresponding_tone": "3",
    },
    {
        "problematic_char": "è",
        "corresponding_char": "e",
        "corresponding_tone": "4",
    },
    {
        "problematic_char": "ō",
        "corresponding_char": "o",
        "corresponding_tone": "1",
    },
    {
        "problematic_char": "ó",
        "corresponding_char": "o",
        "corresponding_tone": "2",
    },
    {
        "problematic_char": "ǒ",
        "corresponding_char": "o",
        "corresponding_tone": "3",
    },
    {
        "problematic_char": "ò",
        "corresponding_char": "o",
        "corresponding_tone": "4",
    },
    {
        "problematic_char": "ū",
        "corresponding_char": "u",
        "corresponding_tone": "1",
    },
    {
        "problematic_char": "ú",
        "corresponding_char": "u",
        "corresponding_tone": "2",
    },
    {
        "problematic_char": "ǔ",
        "corresponding_char": "u",
        "corresponding_tone": "3",
    },
    {
        "problematic_char": "ù",
        "corresponding_char": "u",
        "corresponding_tone": "4",
    },
]


class PinyinAccentRule(TypedDict):
    problematic_char: str
    corresponding_char: str
    corresponding_tone: str


START = [
    "",
    "b",
    "p",
    "m",
    "f",
    "d",
    "t",
    "n",
    "l",
    "z",
    "c",
    "s",
    "zh",
    "ch",
    "sh",
    "r",
    "j",
    "q",
    "x",
    "g",
    "k",
    "h",
    "w",
    "y",
]

FINAL = [
    "a",
    "ai",
    "ao",
    "an",
    "ang",
    "e",
    "ei",
    "en",
    "eng",
    "er",
    "o",
    "ou",
    "ong",
    "i",
    "i*",
    "ia",
    "iao",
    "ie",
    "iu",
    "ian",
    "iang",
    "in",
    "ing",
    "iong",
    "u",
    "ua",
    "uai",
    "ui",
    "uo",
    "uan",
    "uang",
    "un",
    "ueng",
    "ü",
    "üe",
    "üan",
    "ün",
]

INVALID_PINYIN = {
    "ong",
    "i*",
    "be",
    "ber",
    "bou",
    "bong",
    "bi*",
    "bia",
    "biu",
    "biang",
    "biong",
    "bua",
    "buai",
    "bui",
    "buo",
    "buan",
    "buang",
    "bun",
    "bueng",
    "bü",
    "büe",
    "büan",
    "bün",
    "pe",
    "per",
    "pong",
    "pi*",
    "pia",
    "piu",
    "piang",
    "piong",
    "pua",
    "puai",
    "pui",
    "puo",
    "puan",
    "puang",
    "pun",
    "pueng",
    "pü",
    "püe",
    "püan",
    "pün",
    "mer",
    "mong",
    "mi*",
    "mia",
    "miang",
    "miong",
    "mua",
    "muai",
    "mui",
    "muo",
    "muan",
    "muang",
    "mun",
    "mueng",
    "mü",
    "müe",
    "müan",
    "mün",
    "fai",
    "fao",
    "fe",
    "fer",
    "fo",
    "fong",
    "fi",
    "fi*",
    "fia",
    "fiao",
    "fie",
    "fiu",
    "fian",
    "fiang",
    "fin",
    "fing",
    "fiong",
    "fua",
    "fuai",
    "fui",
    "fuo",
    "fuan",
    "fuang",
    "fun",
    "fueng",
    "fü",
    "füe",
    "füan",
    "fün",
    "der",
    "do",
    "di*",
    "dia",
    "diang",
    "din",
    "diong",
    "dua",
    "duai",
    "duang",
    "dueng",
    "dü",
    "düe",
    "düan",
    "dün",
    "tei",
    "ten",
    "ter",
    "to",
    "ti*",
    "tia",
    "tiu",
    "tiang",
    "tin",
    "tiong",
    "tua",
    "tuai",
    "tuang",
    "tueng",
    "tü",
    "tüe",
    "tüan",
    "tün",
    "ner",
    "no",
    "ni*",
    "nia",
    "niong",
    "nua",
    "nuai",
    "nui",
    "nuang",
    "nun",
    "nueng",
    "nüan",
    "nün",
    "len",
    "ler",
    "li*",
    "liong",
    "lua",
    "luai",
    "lui",
    "luang",
    "lueng",
    "lüan",
    "lün",
    "zer",
    "zo",
    "zi",
    "zia",
    "ziao",
    "zie",
    "ziu",
    "zian",
    "ziang",
    "zin",
    "zing",
    "ziong",
    "zua",
    "zuai",
    "zuang",
    "zueng",
    "zü",
    "züe",
    "züan",
    "zün",
    "cer",
    "co",
    "ci",
    "cia",
    "ciao",
    "cie",
    "ciu",
    "cian",
    "ciang",
    "cin",
    "cing",
    "ciong",
    "cua",
    "cuai",
    "cuang",
    "cueng",
    "cü",
    "cüe",
    "cüan",
    "cün",
    "sei",
    "ser",
    "so",
    "si",
    "sia",
    "siao",
    "sie",
    "siu",
    "sian",
    "siang",
    "sin",
    "sing",
    "siong",
    "sua",
    "suai",
    "suang",
    "sueng",
    "sü",
    "süe",
    "süan",
    "sün",
    "zher",
    "zho",
    "zhi",
    "zhia",
    "zhiao",
    "zhie",
    "zhiu",
    "zhian",
    "zhiang",
    "zhin",
    "zhing",
    "zhiong",
    "zhueng",
    "zhü",
    "zhüe",
    "zhüan",
    "zhün",
    "chei",
    "cher",
    "cho",
    "chi",
    "chia",
    "chiao",
    "chie",
    "chiu",
    "chian",
    "chiang",
    "chin",
    "ching",
    "chiong",
    "chueng",
    "chü",
    "chüe",
    "chüan",
    "chün",
    "sher",
    "sho",
    "shong",
    "shi",
    "shia",
    "shiao",
    "shie",
    "shiu",
    "shian",
    "shiang",
    "shin",
    "shing",
    "shiong",
    "shueng",
    "shü",
    "shüe",
    "shüan",
    "shün",
    "ra",
    "rai",
    "rei",
    "rer",
    "ro",
    "ri",
    "ria",
    "riao",
    "rie",
    "riu",
    "rian",
    "riang",
    "rin",
    "ring",
    "riong",
    "ruai",
    "ruang",
    "rueng",
    "rü",
    "rüe",
    "rüan",
    "rün",
    "ja",
    "jai",
    "jao",
    "jan",
    "jang",
    "je",
    "jei",
    "jen",
    "jeng",
    "jer",
    "jo",
    "jou",
    "jong",
    "ji*",
    "jua",
    "juai",
    "jui",
    "juo",
    "juang",
    "jueng",
    "jü",
    "jüe",
    "jüan",
    "jün",
    "qa",
    "qai",
    "qao",
    "qan",
    "qang",
    "qe",
    "qei",
    "qen",
    "qeng",
    "qer",
    "qo",
    "qou",
    "qong",
    "qi*",
    "qua",
    "quai",
    "qui",
    "quo",
    "quang",
    "queng",
    "qü",
    "qüe",
    "qüan",
    "qün",
    "xa",
    "xai",
    "xao",
    "xan",
    "xang",
    "xe",
    "xei",
    "xen",
    "xeng",
    "xer",
    "xo",
    "xou",
    "xong",
    "xi*",
    "xua",
    "xuai",
    "xui",
    "xuo",
    "xuang",
    "xueng",
    "xü",
    "xüe",
    "xüan",
    "xün",
    "ger",
    "go",
    "gi",
    "gi*",
    "gia",
    "giao",
    "gie",
    "giu",
    "gian",
    "giang",
    "gin",
    "ging",
    "giong",
    "gueng",
    "gü",
    "güe",
    "güan",
    "gün",
    "ker",
    "ko",
    "ki",
    "ki*",
    "kia",
    "kiao",
    "kie",
    "kiu",
    "kian",
    "kiang",
    "kin",
    "king",
    "kiong",
    "kueng",
    "kü",
    "küe",
    "küan",
    "kün",
    "her",
    "ho",
    "hi",
    "hi*",
    "hia",
    "hiao",
    "hie",
    "hiu",
    "hian",
    "hiang",
    "hin",
    "hing",
    "hiong",
    "hueng",
    "hü",
    "hüe",
    "hüan",
    "hün",
    "wao",
    "we",
    "wer",
    "wou",
    "wong",
    "wi",
    "wi*",
    "wia",
    "wiao",
    "wie",
    "wiu",
    "wian",
    "wiang",
    "win",
    "wing",
    "wiong",
    "wua",
    "wuai",
    "wui",
    "wuo",
    "wuan",
    "wuang",
    "wun",
    "wueng",
    "wü",
    "wüe",
    "wüan",
    "wün",
    "yai",
    "yei",
    "yen",
    "yeng",
    "yer",
    "yo",
    "yi*",
    "yia",
    "yiao",
    "yie",
    "yiu",
    "yian",
    "yiang",
    "yiong",
    "yu",
    "yua",
    "yuai",
    "yui",
    "yuo",
    "yuan",
    "yuang",
    "yun",
    "yueng",
}

_STARTS_BY_LENGTH = sorted(START, key=len, reverse=True)
_FINAL_SET = set(FINAL)
_VALID_TONES = frozenset({"1", "2", "3", "4"})
_ACCENT_BY_CHAR = {
    rule["problematic_char"]: rule for rule in PINYIN_ACCENT_MAP
}


def _strip_tone(value: str) -> str:
    if value and value[-1] in _VALID_TONES:
        return value[:-1]
    return value


def parse_pinyin_syllable(value: str) -> tuple[str, str] | None:
    trimmed = value.strip().lower()
    if trimmed == "":
        return None

    pinyin = _strip_tone(trimmed)
    if pinyin == "":
        return None

    for start in _STARTS_BY_LENGTH:
        if not pinyin.startswith(start):
            continue
        remainder = pinyin[len(start) :]
        if remainder in _FINAL_SET:
            return start, remainder
    return None


def is_valid_pinyin(value: str) -> bool:
    # Match frontend CharacterFormModal: syllable parses successfully.
    return parse_pinyin_syllable(value) is not None


def suggest_umlaut_pinyin(value: str) -> str | None:
    trimmed = value.strip()
    if trimmed == "" or is_valid_pinyin(trimmed):
        return None
    with_umlaut = trimmed.replace("u", "ü").replace("U", "Ü")
    if with_umlaut != trimmed and is_valid_pinyin(with_umlaut):
        return with_umlaut
    return None


def replace_pinyin_accents(token: str) -> str:
    """Replace accented vowels with plain letters and append tone digit."""
    tone: str | None = None
    chars: list[str] = []
    for char in token:
        rule = _ACCENT_BY_CHAR.get(char)
        if rule is None:
            # Also try lowercase form of the accented character.
            rule = _ACCENT_BY_CHAR.get(char.lower())
            if rule is not None and char.isupper():
                chars.append(rule["corresponding_char"].upper())
                tone = rule["corresponding_tone"]
                continue
        if rule is None:
            chars.append(char)
            continue
        chars.append(rule["corresponding_char"])
        tone = rule["corresponding_tone"]

    result = "".join(chars)
    if tone is None:
        return result
    if result and result[-1] in _VALID_TONES:
        return result[:-1] + tone
    return result + tone


def fix_erhua_syllable(syllable: str) -> str:
    """Erhua suffix split into its own token (e.g. "r" for 儿) is "er", not "r"."""
    tone = syllable[-1] if syllable and syllable[-1] in _VALID_TONES else ""
    base = syllable[:-1] if tone else syllable
    if base == "r":
        return "er" + tone
    return syllable


def normalize_anki_pinyin_token(token: str) -> str | None:
    """Normalize one Anki pinyin syllable to app form (e.g. Qīn → qin1).

    Returns None when the token cannot be made into valid pinyin.
    """
    trimmed = token.strip()
    if trimmed == "":
        return None

    candidate = fix_erhua_syllable(replace_pinyin_accents(trimmed).lower())
    if is_valid_pinyin(candidate):
        return candidate

    umlaut = suggest_umlaut_pinyin(candidate)
    if umlaut is not None:
        return umlaut.lower()

    return None
