"""initial schema

Revision ID: eb7b35a645c6
Revises: 
Create Date: 2026-07-29 14:47:44.957759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7b35a645c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('char', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(length=6), nullable=False),
    sa.Column('writting_known', sa.Boolean(), nullable=False),
    sa.Column('synchronized', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('char')
    )
    op.create_table('hsk_characters',
    sa.Column('character', sa.String(length=1), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('character')
    )
    op.create_table('hsk_words',
    sa.Column('word', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('ignore_vocab_card',
    sa.Column('writting', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('writting')
    )
    op.create_table('ignore_writting_card',
    sa.Column('recto', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('recto')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('token_count',
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('recorded_at', 'type')
    )
    op.create_table('words',
    sa.Column('word', sa.String(length=10), nullable=False),
    sa.Column('definition', sa.String(length=100), nullable=True),
    sa.Column('synchronized', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('character_word',
    sa.Column('character_char', sa.String(), nullable=False),
    sa.Column('word', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['character_char'], ['character.char'], ),
    sa.ForeignKeyConstraint(['word'], ['words.word'], ),
    sa.PrimaryKeyConstraint('character_char', 'word')
    )
    op.create_table('hsk_word_character',
    sa.Column('word', sa.String(length=32), nullable=False),
    sa.Column('character', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['character'], ['hsk_characters.character'], ),
    sa.ForeignKeyConstraint(['word'], ['hsk_words.word'], ),
    sa.PrimaryKeyConstraint('word', 'character')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hsk_word_character')
    op.drop_table('character_word')
    op.drop_table('words')
    op.drop_table('token_count')
    op.drop_table('settings')
    op.drop_table('ignore_writting_card')
    op.drop_table('ignore_vocab_card')
    op.drop_table('hsk_words')
    op.drop_table('hsk_characters')
    op.drop_table('character')
    # ### end Alembic commands ###
